### ISSUE TITLE
Bad directory length

### ISSUE THREAD

**Issue by martin-badin** [di-ninja/babel-plugin-require-context-polyfill#1]
Hello,

I found one issue. Directory length is bad. The variable `contextDir` contains on the end `/` char.

Bad
```const contextDirLen = contextDir.length + 1;```

Good
```const contextDirLen = contextDir.length;```

**Comment by devthejo** [comment]
I use it on a react-native project and I've not this issue, I have to add some unit tests on this project to improve debugging, I will do that shortly. Can you tell me what is your environnement (node, webpack, react-native), babel version etc...

**Comment by martin-badin** [comment]
macOS Mojave 10.14
Node 10.9.0
Babel 6.26.3
Browser Sync 2.26.3
Gulp 4.0.0

**Comment by devthejo** [comment]
I've writed it for babel 7, try to upgrade your babel version and see if that fix your problem. I don't use gulp myself, so If you can provide me a full example to reproduce this error, I can try to fix it.

**Comment by martin-badin** [comment]
Ok, I try it for babel 7.

**Comment by martin-badin** [comment]
Hello, I trying this package with babel 7, but still missing the first character from the file name. I try on this [template](https://github.com/martin-badin/vue-gulp-template)

**Comment by devthejo** [comment]
Can you give me more details:
the input directory variable path and produced path
the complete stacktrace from the console error report

**Comment by martin-badin** [comment]
```
const req = require.context('./', false, /\.vue$/);

req.keys().forEach(key => {
  console.log(key);
});
```

<img width="541" alt="snimka obrazovky 2018-10-23 o 19 27 28" src="https://user-images.githubusercontent.com/5845264/47379036-15295b00-d6fa-11e8-8c16-9465764793a4.png">

**Comment by devthejo** [comment]
try to remove the trailing slash from directory as:

`const req = require.context('.', false, /\.vue$/)`

**Comment by martin-badin** [comment]
build error

```
const req = require.context('.', false, /\.vue$/);
```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object while parsing file:
```

**Comment by devthejo** [comment]
OK, after some investigations I understand that is babel-plugin-module-resolver that doesn't support resolution of '.', I just added some tests and a bugfix, try to upgrade to just publised now version 1.0.1 and keep path without trailing slash

`$ npm i -D babel-plugin-module-resolver@latest`

`const req = require.context('.', false, /\.vue$/);`

**Comment by martin-badin** [comment]
does not work, it shows the same error. I use yarn

**Comment by devthejo** [comment]
can you show me the stacktrace ?
are you using the version 1.1.1 ?
