### ISSUE TITLE
Pattern is udefined

### ISSUE THREAD

**Issue by martin-badin** [di-ninja/babel-plugin-require-context-polyfill#2]
Hello,

The variable `pattern` is undefined. Below is my code.

```require.context('./', false, /\.vue$/)```

**Comment by devthejo** [comment]
Can you add your stacktrace, because I don't see any obvious error in the code of babel-plugin-require-context-polyfill that can cause this

**Comment by martin-badin** [comment]
If I write them regex as a string, `pattern` contains this string. But regex not working.

macOS Mojave 10.14
Node 10.9.0
Babel 6.26.3
Browser Sync 2.26.3
Gulp 4.0.0

**Comment by devthejo** [comment]
The stacktrace is the full error details, so I can see what line and each function that are responsible for the error.

**Comment by martin-badin** [comment]
I try first upgrade babel to version 7.
